[build]
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://breslev-torah-api.onrender.com"
  NEXT_PUBLIC_ENVIRONMENT = "production"

[[redirects]]
  from = "/api/*"
  to = "https://breslev-torah-api.onrender.com/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200