[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "backend"
port = 8000

[services.backend]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1"
numReplicas = 1
region = "us-west"

[[services.backend.envs]]
NODE_ENV = "production"
ENVIRONMENT = "production"
DATABASE_URL = "${{POSTGRES.DATABASE_URL}}"
REDIS_URL = "${{REDIS.REDIS_URL}}"

[[plugins]]
name = "postgres"
plan = "starter"

[[plugins]]
name = "redis"
plan = "starter"