"""Initial tables with UUID fixes

Revision ID: c108b553a0cb
Revises: 20250709_064852
Create Date: 2025-07-09 07:33:29.111574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c108b553a0cb'
down_revision: Union[str, None] = '20250709_064852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sa.Enum('CHASIDUT', 'KABBALAH', 'LITURGY', 'BIOGRAPHY', 'STORIES', name='bookcategory'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parts', sa.Integer(), nullable=False),
    sa.Column('chapters', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('bookmark_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_slug'), 'books', ['slug'], unique=True)
    op.create_index(op.f('ix_books_title'), 'books', ['title'], unique=False)
    op.create_table('chat_messages',
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='chatrole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message_metadata', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context_used', sa.Boolean(), nullable=False),
    sa.Column('citations', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model_used', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SCHOLAR', 'STUDENT', 'GUEST', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('study_level', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('study_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'REVIEWED', name='studystatus'), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_studied_at', sa.DateTime(), nullable=False),
    sa.Column('comprehension_score', sa.Float(), nullable=True),
    sa.Column('notes_count', sa.Integer(), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('study_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_progress_book_id'), 'study_progress', ['book_id'], unique=False)
    op.create_index(op.f('ix_study_progress_user_id'), 'study_progress', ['user_id'], unique=False)
    op.create_table('study_streaks',
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_days_studied', sa.Integer(), nullable=False),
    sa.Column('last_study_date', sa.Date(), nullable=True),
    sa.Column('streak_start_date', sa.Date(), nullable=True),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=False),
    sa.Column('weekly_goal_chapters', sa.Integer(), nullable=False),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('texts',
    sa.Column('ref', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('book_slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=True),
    sa.Column('verse', sa.Integer(), nullable=True),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('hebrew', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('english', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('french', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('full_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sefaria_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_texts_book_slug'), 'texts', ['book_slug'], unique=False)
    op.create_index(op.f('ix_texts_chapter'), 'texts', ['chapter'], unique=False)
    op.create_index(op.f('ix_texts_ref'), 'texts', ['ref'], unique=False)
    op.create_index(op.f('ix_texts_verse'), 'texts', ['verse'], unique=False)
    op.create_table('bookmarks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Uuid(), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse', sa.Integer(), nullable=True),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmarks_book_id'), 'bookmarks', ['book_id'], unique=False)
    op.create_index(op.f('ix_bookmarks_user_id'), 'bookmarks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmarks_user_id'), table_name='bookmarks')
    op.drop_index(op.f('ix_bookmarks_book_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_texts_verse'), table_name='texts')
    op.drop_index(op.f('ix_texts_ref'), table_name='texts')
    op.drop_index(op.f('ix_texts_chapter'), table_name='texts')
    op.drop_index(op.f('ix_texts_book_slug'), table_name='texts')
    op.drop_table('texts')
    op.drop_table('study_streaks')
    op.drop_index(op.f('ix_study_progress_user_id'), table_name='study_progress')
    op.drop_index(op.f('ix_study_progress_book_id'), table_name='study_progress')
    op.drop_table('study_progress')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_slug'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
